---
- name: Check disk space usage
  hosts: all
  tasks:
    
     - name: Check disk space usage on servers
       shell: df -Th| grep -w "run"
       register: result
     - debug:
          var: result.stdout_lines
       when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
