---
- name: Create a new Demo EC2 instance
  hosts: local
  connection: local
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-01e074f40dfb9999d  # Ubuntu 16.04 LTS
      keypair: 01282020 # pem file name

  vars_files:
     - pass.yml
  tasks:

    - name: Create an ec2 instance
      ec2:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         key_name: "{{ keypair }}"
         group: JCP  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         vpc_subnet_id: subnet-4a002f22
         assign_public_ip: yes
      register: ec2_machine